id = "sops"
name = "sops"
version = "0.1.0"
schema_version = 1
authors = ["Josh Simmonds <github@beholdthehurricane.com>"]
description = "Sops Encryption/Decryption support for Zed"
repository = "https://github.com/j0sh3rs/sops-zed"

[context_servers.sops]
name = "Sops"
